server:
  port: 8090
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
  routes:
    - id: ms-adduser
      uri: lb://adduser
      predicates:
        - Path=/adduser/**
    - id: ms-creditsimulation
      uri: lb://creditsimulation
      predicates:
        - Path=/creditsimulation/**
  