server:
  port: 8090
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
  routes:
    - id: ms-adduser
      uri: lb://adduser
      predicates:
        - Path=/adduser/**
    - id: ms-creditsimulation
      uri: lb://creditsimulation
      predicates:
        - Path=/executives/**
    - id: ms-creditapplication
      uri: lb://creditapplication
      predicates:
        - Path=/api/executives/**,/api/v1/credit_application/**,/api/v1/document/**
    - id: ms-evaluatecredit
      uri: lb://evaluatecredit
      predicates:
        - Path=/api/executives/**,/api/v1/client-bank-account/**,/api/v1/debt/**,/api/v1/employmentHistory/**