apiVersion: v1
kind: PersistentVolume
metadata:
  name: creditsimulation-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/creditsimulation-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creditsimulation-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditsimulation-db-deployment
  labels:
    app: creditsimulation-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: creditsimulation-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: creditsimulation-db-deployment
        tier: database
    spec:
      containers:
        - name: creditsimulation-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: creditsimulation-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: creditsimulation-db-storage
          persistentVolumeClaim:
            claimName: creditsimulation-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: creditsimulation-db-service
  labels:
    app: creditsimulation-db-service
    tier: database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: creditsimulation-db-deployment
    tier: database
  type: LoadBalancer