apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creditapplication-deployment
  labels:
    app: ms-creditapplication-deployment
spec:
  selector:
    matchLabels:
      app: ms-creditapplication-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-creditapplication-deployment
    spec:
      containers:
        - name: ms-creditapplication
          image: benjasepulvedaflores/ms-creditapplication
          ports:
            - containerPort: 8003
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITAPPLICATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDITAPPLICATION
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_CREDITAPPLICATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD


